"""Render the attribution engine's output into the file artifacts a triage workflow
reads: an `incidents.jsonl` (one row per outcome) and a human-readable `report.md`.

These engine caveats are preserved unchanged: a binding's confidence is the scored
recency/coverage signal (the identity calibrator), NOT a field-calibrated probability,
and FieldLoop builds an evidence package for a human to confirm rather than asserting a
root cause. Both are stated in the report so a reader cannot mistake the score for a
calibrated likelihood.
"""

from __future__ import annotations

from typing import Any


def build_incidents(
    feedbacks: list[dict[str, Any]], skipped: list[dict[str, Any]]
) -> list[dict[str, Any]]:
    """One incident row per outcome: an attributed binding (which decision, by what
    method, at what scored confidence), or an unattributed outcome carrying the engine's
    own skip reason. Sorted by outcome id so the file is stable and diffable across runs.
    """
    incidents: list[dict[str, Any]] = []
    for fb in feedbacks:
        incidents.append(
            {
                "outcome_id": fb.get("source_outcome_id"),
                "state": "attributed",
                "target_type": fb.get("target_type"),
                "bound_target_id": fb.get("target_id"),
                "join_method": fb.get("join_method"),
                "confidence": fb.get("join_confidence"),
                "delay_ms": fb.get("delay_ms"),
                "metric_name": fb.get("metric_name"),
            }
        )
    for sk in skipped:
        incidents.append(
            {
                "outcome_id": sk.get("outcome_id"),
                "outcome_kind": sk.get("outcome_kind"),
                "state": "unattributed",
                "reason": sk.get("reason"),
            }
        )
    # An unattributed outcome has no source feedback id of its own form, but both rows
    # carry `outcome_id`; sort on it (empty-string fallback keeps a None from raising).
    incidents.sort(key=lambda row: row.get("outcome_id") or "")
    return incidents


def _confidence_cell(value: Any) -> str:
    """Two-decimal confidence, or an em dash when absent (a synthetic-absence row may
    carry none) — never a misleading 0.00."""
    if isinstance(value, (int, float)):
        return f"{value:.2f}"
    return "—"


def build_report_md(incidents: list[dict[str, Any]]) -> str:
    """Render the incident list as Markdown: an attributed table, an unattributed table,
    and a count summary, preceded by the confidence calibration caveats."""
    attributed = [i for i in incidents if i["state"] == "attributed"]
    unattributed = [i for i in incidents if i["state"] == "unattributed"]

    lines = [
        "# FieldLoop attribution report",
        "",
        "Generated by `fieldloop attribute` over an imported MCAP file.",
        "",
        "Confidence is a scored recency/coverage signal (the identity calibrator), "
        "not a field-calibrated probability: a 0.87 means \"close and well-covered\", "
        "not \"87% of such bindings proved correct\". FieldLoop builds an evidence "
        "package — the method, the confidence, and the bound decision — for a human to "
        "confirm; it does not assert a root cause.",
        "",
        "## Attributed incidents",
        "",
        "| outcome | method | confidence | bound decision | delay (ms) |",
        "| --- | --- | ---: | --- | ---: |",
    ]
    for inc in attributed:
        delay = inc.get("delay_ms")
        lines.append(
            "| {outcome} | {method} | {conf} | {target} | {delay} |".format(
                outcome=inc.get("outcome_id"),
                method=inc.get("join_method"),
                conf=_confidence_cell(inc.get("confidence")),
                target=inc.get("bound_target_id"),
                delay=delay if delay is not None else "—",
            )
        )

    lines += [
        "",
        "## Unattributed outcomes",
        "",
        "| outcome | kind | reason |",
        "| --- | --- | --- |",
    ]
    for inc in unattributed:
        lines.append(
            f"| {inc.get('outcome_id')} | {inc.get('outcome_kind')} | {inc.get('reason')} |"
        )

    lines += [
        "",
        "## Summary",
        "",
        f"- outcomes attributed: {len(attributed)}",
        f"- outcomes unattributed: {len(unattributed)}",
        "",
    ]
    return "\n".join(lines) + "\n"
